import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  output: 'export',
  // Static export has no image server: images are pre-generated by scripts/optimize-images.mjs.
  images: { loader: 'custom', loaderFile: './lib/imageLoader.ts' },
  trailingSlash: false,
};

export default nextConfig;
