// Responsive AVIF/WebP background image (generated by scripts/optimize-images.mjs),
// with the original JPEG as fallback. Sized by the parent's CSS (object-fit: cover).
const widths = [1200, 1920, 2400];

export const bgSrcSet = (name: string, ext: 'avif' | 'webp') =>
  widths.map((w) => `/images/optimized/${name}-${w}.${ext} ${w}w`).join(', ');

type Props = { name: string; src: string; width: number; height: number; eager?: boolean };

export default function BgPicture({ name, src, width, height, eager }: Props) {
  return (
    <picture>
      <source type="image/avif" srcSet={bgSrcSet(name, 'avif')} sizes="100vw" />
      <source type="image/webp" srcSet={bgSrcSet(name, 'webp')} sizes="100vw" />
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={src}
        alt=""
        width={width}
        height={height}
        sizes="100vw"
        decoding={eager ? 'sync' : 'async'}
        loading={eager ? 'eager' : 'lazy'}
        fetchPriority={eager ? 'high' : undefined}
      />
    </picture>
  );
}
